---
title: Attila Gyetvai
---
```{r include=FALSE}
coauthors <- data.frame(
  name = c("Peter Arcidiacono", 
           "Arnaud Maurel", 
           "Maria Zhu", 
           "Katya Jardim",
           "Nasir Hossein Dad",
           "Eugene Tan",
           "Nic Kozeniauskas",
           "Anikó Bíró",
           "István Boza",
           "Dániel Prinz"),
  website = c("http://public.econ.duke.edu/~psarcidi/", 
              "http://www.amaurel.net", 
              "http://www.mariazhu.com", 
              "https://ekaterinajardim.com",
              "https://sites.google.com/view/nasirhosseindad",
              "https://sites.google.com/site/econeugenetan",
              "http://nicjkoz.com",
              "https://sites.google.com/site/aniko17biro/",
              "https://sites.google.com/view/bozaistvan/",
              "http://danielpri.nz")
)
link <- paste0("<a href=\"", coauthors$website, "\" class=link>",coauthors$name,"</a>")
coauthors <- cbind(coauthors, link)
row.names(coauthors) <- coauthors$name
```

<p class=big>
  I, Attila Gyetvai, am a research economist. I am currently on leave from the Bank of Portugal and visiting the University of Florida.
  <a class=link href="cv_attila_gyetvai.pdf">Here is my CV</a>. 
  You can reach me at <a class=link href="mailto:agyetvai@ufl.edu">agyetvai@ufl.edu</a>.
</p>
<p class=big>
  Here are my working papers:
  <ul>
    <li>"<a class=link href="research/gt_entrep_hc_risk.pdf">The Role of Human Capital Specificity in Entrepreneurship</a>" with `r coauthors["Eugene Tan","link"]`</li>
    <li>"<a class=link href="research/agmj_ccp_search.pdf">Identification and Estimation of Continuous-Time Job Search Models</a>" with `r coauthors["Peter Arcidiacono","link"]`, `r coauthors["Arnaud Maurel","link"]`, and `r coauthors["Katya Jardim","link"]`, R&R at <i><b>The Review of Economic Studies</b></i></li>
    <li>"<a class=link href="research/bbgp_health_shocks.pdf">Health Shocks, Social Insurance, and Firms</a>" with `r coauthors["Anikó Bíró","link"]`, `r coauthors["István Boza","link"]`, and `r coauthors["Dániel Prinz","link"]`</li>
    <li>"<a class=link href="research/g_option_value_occs.pdf">The Option Value of Occupations</a>"</li>
  </ul>
</p>
<p class=big>
  And here are my publications:
  <ul>
    <li>"<a class=link href="research/gz_coworker_networks.pdf">Coworker Networks and the Role of Occupations in Job Finding</a>" with `r coauthors["Maria Zhu","link"]`, <a class=link href="https://doi.org/10.1016/j.labeco.2025.102699"><i><b>Labour Economics</b></i></a> (2025), <a class=link href="research/gz_coworker_networks_code.zip">code</a></li>
  </ul>
</p>