---
title: Attila Gyetvai
---
<h1 class=name>   <a href="index.html" class=name> Attila Gyetvai </a> </h1>
<h1 class=affil>  PhD Candidate in Economics, Duke University </h1>
<h1 class=navbar> <a href="research.html" class=name> RESEARCH </a> &nbsp; &nbsp; &nbsp; <a href="CV_AttilaGyetvai.pdf" class=name> CV </a> </h1>

```{r include=FALSE}
coauthors <- data.frame(
  name = c("Peter Arcidiacono", "Arnaud Maurel", "Maria Zhu", "Ekaterina Jardim"),
  website = c("http://public.econ.duke.edu/~psarcidi/", "http://www.amaurel.net", "http://www.mariazhu.com", "https://ekaterinajardim.com")
)
link <- paste0("<a href=\"", coauthors$website, "\">",coauthors$name,"</a>")
coauthors <- cbind(coauthors, link)
row.names(coauthors) <- coauthors$name
```

<!--
<ul>
  <li><h2>Working Papers</h2></li>
  <li>
  <p class=papertitle> <a href="ojs.pdf"><b><u>Job Mobility Within and Across Occupations</b></u></a> (Job Market Paper) </p>
  <p class=paperdet> <i> Abstract: </i> 
  This paper assesses the impact of occupations on the inequality of wages over the life cycle. 
  I build and estimate a structural model of mobility in which workers climb one of many job ladders, each associated with an occupation, and may jump from one ladder to another. 
  The key sources of heterogeneity are occupation-specific offer arrival rates, job separation rates, compensating differentials, and switching costs. 
  Using rich longitudinal data from Hungarian administrative records, I uncover substantial heterogeneity in the underlying determinants of job flows that capture workers' opportunities to climb the occupational job ladders as well as their preferences for occupations. 
  Simulating career paths, I show that workers who start their careers in low-paying jobs in a high-skill occupation quickly surpass their high-wage peers in low-skill occupations. 
  I demonstrate that occupational heterogeneity explains the life-cycle profile of inequality in wages. 
  </p> </li>
  
  <li> 
  <p class=papertitle> <a href="ccp-cont.pdf"><b><u>Conditional Choice Probability Estimation of Continuous-Time Job Search Models</u></b></a> </br>
  with <a href="http://public.econ.duke.edu/~psarcidi/">Peter Arcidiacono</a>, <a href="https://ekaterinajardim.com">Ekaterina Jardim</a>, and <a href="http://www.amaurel.net">Arnaud Maurel</a> </p>
  <p class=paperdet> <i> Abstract: </i> 
  In this paper we propose a new method to estimate continuous-time job search models. 
  Our approach is based on an adaptation of the conditional choice probability estimation methods to a continuous-time job search environment. 
  To do so, the proposed framework incorporates preference shocks into the search framework, resulting in a tight connection between value functions and conditional choice probabilities. 
  A key advantage of the proposed approach relative to standard estimation methods for continuous-time job search models is computational. 
  In particular, this makes it possible to estimate rich nonstationary job search models without having to solve any differential equation, and in some cases even avoiding any optimization. 
  We apply our method to analyze the effect of unemployment benefit expiration on the duration of unemployment using rich longitudinal data from Hungarian administrative records.
  </p> </li>
  
  <li> 
  <p class=papertitle> <a href="wn.pdf"><b><u>Coworker Networks and the Role of Occupations in Job Finding</u></b></a> </br>
  with <a href="http://www.mariazhu.com">Maria Zhu</a></p>
  <p class=paperdet> <i> Abstract: </i> 
  Which former coworkers help displaced workers find jobs? 
  We answer this question by studying occupational similarity in job finding networks. 
  Using administrative matched employer-employee data from Hungary, this paper relates the unemployment duration of displaced workers to the employment rate in the networks of their former coworkers in various occupations. 
  We find that only those former coworkers are helpful in the job finding process who worked in the same narrow occupation as the displaced worker. 
  However, effects vary along educational levels: for displaced workers in occupations that require little to no education, coworkers in the same narrow occupation matter; for those in occupations requiring more education, coworkers in different occupations reduce unemployment.
  </p> </li>
</ul>

-->
<ul>
  <li><h2>Work in Progress</h2></li>
  <li> 
  <p class=papertitle> <b>Job Mobility Within and Across Occupations</b> (Job Market Paper) </p>
  <p class=paperdet> <i> Abstract: </i> 
  This paper assesses the impact of occupations on the inequality of wages over the life cycle. 
  I document that occupations offer diverging wage trajectories to their workers.
  I then propose a structural model of mobility that gives rise to such diverging occupational wage trajectories.
  In the model, workers climb one of many job ladders, each associated with an occupation, and can jump from one ladder to another. 
  The key sources of heterogeneity are occupation-specific offer arrival rates, job separation rates, nonwage amenities, and switching costs. 
  Estimating the model on Hungarian administrative data that track workers' occupational employment histories, I uncover substantial heterogeneity in the underlying determinants of job flows that capture workers' opportunities to climb the occupational job ladders as well as their preferences for occupations. 
  Simulating career paths, I show that occupational heterogeneity explains the life cycle profile of inequality in wages. 
  </p> </li>
  
  <li> 
  <p class=papertitle> <b>Conditional Choice Probability Estimation of Continuous-Time Job Search Models</b> </br>
  with `r coauthors["Peter Arcidiacono","link"]`, `r coauthors["Ekaterina Jardim","link"]`, and `r coauthors["Arnaud Maurel","link"]` </p>
  <p class=paperdet> <i> Abstract: </i> 
  We propose a new method to estimate continuous-time job search models. 
Our approach is based on an adaptation of the conditional choice probability estimation methods to a continuous-time job search environment. To do so, the proposed framework incorporates preference shocks into the search framework, resulting in a tight connection between value functions and conditional choice probabilities. 
Our method, relative to standard estimation methods for continuous-time job search models, yields considerable computational gains. 
In particular, we can estimate rich nonstationary job search models without having to solve any differential equations, and in some cases even avoiding any optimization. 
We apply our method to analyze the effect of unemployment benefit expiration on the duration of unemployment using rich longitudinal data from Hungarian administrative records.
  </p> </li>
  
  <li> 
  <p class=papertitle> <b>Coworker Networks and the Role of Occupations in Job Finding</b> </br>
  with `r coauthors["Maria Zhu","link"]`</p>
  <p class=paperdet> <i> Abstract: </i> 
  Which former coworkers help displaced workers find jobs? 
  We answer this question by studying occupational similarity in job finding networks. 
  Using administrative matched employer-employee data from Hungary, this paper relates the unemployment duration of displaced workers to the employment rate in the networks of their former coworkers in various occupations. 
  We find that coworkers of all occupational backgrounds are helpful in the job finding process, but coworkers who worked in the same narrow occupation as the displaced worker are significantly more useful. 
  Additionally, effects vary substantially along skill levels: for displaced workers in occupations that require little to no education, coworkers in the same narrow occupation matter; for those in occupations requiring more education, coworkers in different occupations reduce unemployment.
  </p> </li>
  
  <li> 
  <p class=papertitle> <b>Occupational Structure and Firm Performance</b></p>
  </li>
</ul>

